"use client";

import { useEffect, useMemo, useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight } from "lucide-react";
import { addDays, arrivalDateFor, buildFridayDates, getDepartureDecision, holidayName, isoDate, todayPlusDays } from "@/data/departureCalendar";

type Props = { duration?: string; isGroup?: boolean; selectedDate: string; onSelect: (date: string) => void };
function formatMonth(value: string) { return new Date(`${value}-01T12:00:00`).toLocaleDateString("en-IN", { month: "long", year: "numeric" }); }
function formatDate(value: string) { return new Date(`${value}T12:00:00`).toLocaleDateString("en-IN", { weekday: "short", day: "2-digit", month: "short", year: "numeric" }); }

export default function DepartureCalendar({ duration, isGroup = false, selectedDate, onSelect }: Props) {
  const minimumDate = todayPlusDays(7);
  const months = useMemo(() => { const start = new Date(`${new Date().getFullYear()}-${String(new Date().getMonth() + 1).padStart(2, "0")}-01T12:00:00`); const end = new Date("2027-12-01T12:00:00"); const result: string[] = []; let cursor = start; while (cursor <= end) { result.push(isoDate(cursor).slice(0, 7)); cursor = new Date(cursor.getFullYear(), cursor.getMonth() + 1, 1, 12); } return result; }, []);
  const selectedIndex = Math.max(0, months.indexOf(selectedDate.slice(0, 7)));
  const [monthIndex, setMonthIndex] = useState(selectedIndex);
  useEffect(() => { setMonthIndex((current) => selectedIndex !== current && selectedDate ? selectedIndex : current); }, [selectedIndex, selectedDate]);
  const currentMonth = months[Math.min(monthIndex, months.length - 1)] ?? months[0];
  const monthStart = new Date(`${currentMonth}-01T12:00:00`); const firstWeekday = monthStart.getDay(); const daysInMonth = new Date(monthStart.getFullYear(), monthStart.getMonth() + 1, 0).getDate();
  const groupDates = useMemo(() => new Set(buildFridayDates(minimumDate)), [minimumDate]);
  const cells = Array.from({ length: firstWeekday + daysInMonth }, (_, index) => index - firstWeekday + 1);
  const selectedDecision = selectedDate ? getDepartureDecision(selectedDate, duration) : null; const selectedArrival = selectedDate ? arrivalDateFor(selectedDate, duration) : ""; const selectedHoliday = selectedDate ? holidayName(selectedDate) : undefined;
  const chooseMonth = (nextIndex: number) => { const safeIndex = Math.max(0, Math.min(months.length - 1, nextIndex)); setMonthIndex(safeIndex); const month = months[safeIndex]; const firstAvailable = Array.from({ length: new Date(new Date(`${month}-01T12:00:00`).getFullYear(), new Date(`${month}-01T12:00:00`).getMonth() + 1, 0).getDate() }, (_, i) => `${month}-${String(i + 1).padStart(2, "0")}`).find((date) => { const groupAllowed = !isGroup || groupDates.has(date); return groupAllowed && date >= minimumDate; }); if (firstAvailable) onSelect(firstAvailable); };

  return <section className="border-t border-slate-200 bg-slate-50 px-5 py-5"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><CalendarDays size={19} className="text-[#153e75]"/><h3 className="text-lg font-extrabold text-slate-900">Departure Calendar</h3></div><p className="mt-1 text-xs text-slate-500">Minimum 7-day advance • 2026–27 holiday blackout • {isGroup ? "Group departures follow the published Friday schedule." : "Select any available future travel date."}</p></div><span className="rounded-full bg-white px-3 py-1.5 text-[11px] font-extrabold text-slate-600 ring-1 ring-slate-200">Travel date</span></div>
    <div className="mt-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between gap-3"><button type="button" disabled={monthIndex <= 0} onClick={() => chooseMonth(monthIndex - 1)} className="rounded-lg p-2 text-slate-600 hover:bg-slate-100 disabled:opacity-30"><ChevronLeft size={18}/></button><p className="text-sm font-extrabold text-slate-900">{formatMonth(currentMonth)}</p><button type="button" disabled={monthIndex >= months.length - 1} onClick={() => chooseMonth(monthIndex + 1)} className="rounded-lg p-2 text-slate-600 hover:bg-slate-100 disabled:opacity-30"><ChevronRight size={18}/></button></div><div className="mt-3 grid grid-cols-7 text-center text-[10px] font-bold uppercase tracking-wide text-slate-400"><span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span></div><div className="mt-2 grid grid-cols-7 gap-1.5">{cells.map((day, index) => { if(day<1)return <span key={`blank-${index}`} className="h-10"/>; const date=`${currentMonth}-${String(day).padStart(2,"0")}`; const decision=getDepartureDecision(date,duration); const groupAllowed=!isGroup||groupDates.has(date); const available=groupAllowed&&date>=minimumDate; const selected=date===selectedDate; const holiday=holidayName(date); const className=!available?"bg-slate-100 text-slate-300":decision.bookable?(selected?"bg-[#153e75] text-white ring-2 ring-blue-200":"bg-emerald-50 text-emerald-800 hover:bg-emerald-100"):(selected?"bg-orange-600 text-white ring-2 ring-orange-200":"bg-rose-50 text-rose-700 hover:bg-rose-100"); return <button key={date} type="button" disabled={!available} onClick={()=>onSelect(date)} title={!available?(isGroup&&!groupAllowed?"No published group departure on this date.":"Not available for online selection."):holiday?`${holiday} — enquiry only`:decision.bookable?"Online booking available":decision.reason} className={`relative flex h-10 items-center justify-center rounded-lg text-xs font-extrabold transition ${className}`}>{day}{holiday&&available&&<span className="absolute bottom-1 h-1 w-1 rounded-full bg-current opacity-80"/>}</button>; })}</div><div className="mt-4 flex flex-wrap gap-3 text-[11px] font-semibold text-slate-500"><span className="flex items-center gap-1.5"><i className="h-2.5 w-2.5 rounded-full bg-emerald-500"/> Online booking</span><span className="flex items-center gap-1.5"><i className="h-2.5 w-2.5 rounded-full bg-rose-500"/> Enquiry only</span><span className="flex items-center gap-1.5"><i className="h-2.5 w-2.5 rounded-full bg-slate-300"/> Not available</span></div></div>
    {selectedDate&&<div className={`mt-3 rounded-xl border px-4 py-3 ${selectedDecision?.bookable?"border-emerald-200 bg-emerald-50":"border-orange-200 bg-orange-50"}`}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Selected departure</p><p className="mt-1 font-extrabold text-slate-900">{formatDate(selectedDate)} <span className="font-semibold text-slate-500">→ {formatDate(selectedArrival)}</span></p></div><span className={`rounded-full px-3 py-1.5 text-xs font-extrabold ${selectedDecision?.bookable?"bg-emerald-600 text-white":"bg-orange-600 text-white"}`}>{selectedDecision?.bookable?"Online Booking Available":"Enquiry Only"}</span></div>{!selectedDecision?.bookable&&<p className="mt-2 text-xs font-semibold text-orange-800">{selectedDecision?.reason}{selectedHoliday?` Holiday: ${selectedHoliday}.`:""}</p>}</div>}
  </section>;
}
