import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CheckCircle2, MapPinned, Sparkles } from "lucide-react";

const baseUrl = "https://www.onlyroadtrip.com";
export const metadata: Metadata = {
  title: "Prayagraj Yatra Package from Delhi | Sangam & Mahakumbh Tour | Only Road Trip",
  description: "Plan a customized Prayagraj Yatra from Delhi with Triveni Sangam, temples, comfortable transport, hotel coordination and flexible pilgrimage itineraries.",
  keywords: ["Prayagraj Yatra Package", "Prayagraj Yatra Package from Delhi", "Prayagraj Tour Package", "Triveni Sangam Tour", "Prayagraj Pilgrimage Package", "Prayagraj Yatra Booking"],
  alternates: { canonical: `${baseUrl}/prayagraj-yatra-package` },
  robots: { index: true, follow: true },
};
const faqs = [
  ["Can I book a Prayagraj Yatra package from Delhi?", "Yes. We can plan a customized Prayagraj trip from Delhi with suitable transport, accommodation and sightseeing based on your dates and group size."],
  ["Can Prayagraj be combined with Kashi and Ayodhya?", "Yes. Kashi, Ayodhya and Prayagraj can be combined into one customized spiritual circuit."],
  ["Can senior citizens travel on this package?", "Yes. We can discuss a comfortable itinerary with suitable road travel, rest stops and accommodation. Travelers should consider their individual fitness and medical advice."],
];
export default function PrayagrajPage() {
  return <main className="min-h-screen bg-white text-slate-900">
    <section className="relative overflow-hidden border-b border-slate-100"><div className="absolute -right-24 top-0 h-[500px] w-[500px] rounded-full bg-blue-50 blur-3xl"/><div className="relative mx-auto max-w-7xl px-6 pb-20 pt-32 lg:px-8 lg:pb-28 lg:pt-40"><div className="max-w-4xl"><div className="inline-flex items-center gap-2 rounded-full border border-blue-100 bg-blue-50 px-4 py-2 text-xs font-bold uppercase tracking-[.2em] text-blue-800"><Sparkles size={15}/> Prayagraj Yatra Packages</div><h1 className="mt-7 text-5xl font-semibold leading-[1.05] tracking-tight md:text-6xl lg:text-7xl">Prayagraj Yatra Package from Delhi<span className="mt-3 block text-blue-800">A meaningful journey to Sangam.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-600 md:text-xl">Plan a customized Prayagraj pilgrimage with Triveni Sangam, important temples, comfortable transportation, hotel coordination and a practical itinerary from Only Road Trip.</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/contact" className="inline-flex items-center gap-2 rounded-full bg-blue-800 px-7 py-3.5 text-sm font-bold text-white">Get Prayagraj Quote <ArrowRight size={18}/></Link><Link href="/kashi-ayodhya-prayagraj-yatra-package" className="inline-flex items-center gap-2 rounded-full border border-slate-200 px-7 py-3.5 text-sm font-bold">Kashi + Ayodhya + Prayagraj</Link></div></div></div></section>
    <section className="py-20 lg:py-24"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-blue-700">Prayagraj Travel Planning</p><h2 className="mt-4 text-4xl font-semibold md:text-5xl">A pilgrimage itinerary built around your pace.</h2></div><div className="space-y-5 text-lg leading-8 text-slate-600"><p>Prayagraj is an important spiritual destination known for the Triveni Sangam and its rich religious heritage. We help bring transport, stays and sightseeing into one clear travel plan.</p><p>Choose a short Prayagraj visit or combine it with Kashi and Ayodhya for a broader Uttar Pradesh pilgrimage circuit.</p></div></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[["Triveni Sangam","Plan a visit to the sacred confluence and nearby spiritual sites."],["Temple Visits","Include important temples and local pilgrimage attractions in your itinerary."],["Comfortable Travel","Vehicle options can be planned for couples, families and groups."],["Flexible Itinerary","Customize nights, departure point, sightseeing and pace around your requirements."]].map(([t,x])=><div key={t} className="rounded-3xl border border-slate-200 p-7 shadow-sm"><MapPinned className="text-blue-800" size={22}/><h3 className="mt-5 text-xl font-semibold">{t}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{x}</p></div>)}</div></div></section>
    <section className="bg-slate-50 py-20"><div className="mx-auto max-w-7xl px-6 lg:px-8"><h2 className="text-4xl font-semibold md:text-5xl">Why plan your Prayagraj Yatra with Only Road Trip?</h2><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{["Customized travel dates and departure points","Comfort-focused transport and stay options","Family and senior-citizen travel planning","Clear itinerary before booking","Kashi, Ayodhya and Prayagraj circuit options","Personalized travel coordination"].map(x=><div key={x} className="flex gap-3 rounded-2xl border border-slate-200 bg-white p-5"><CheckCircle2 className="shrink-0 text-blue-800" size={20}/><span className="text-sm leading-6">{x}</span></div>)}</div></div></section>
    <section className="py-20"><div className="mx-auto max-w-4xl px-6 lg:px-8"><h2 className="text-4xl font-semibold">Frequently Asked Questions</h2><div className="mt-10 space-y-4">{faqs.map(([q,a])=><details key={q} className="rounded-2xl border border-slate-200 p-5"><summary className="cursor-pointer font-semibold">{q}</summary><p className="mt-3 text-sm leading-7 text-slate-600">{a}</p></details>)}</div><div className="mt-12 rounded-3xl bg-blue-800 p-8 text-white"><h2 className="text-3xl font-semibold">Plan your Prayagraj Yatra</h2><p className="mt-3 text-blue-100">Share your dates, group size and departure city and we will prepare suitable options.</p><Link href="/contact" className="mt-6 inline-flex items-center gap-2 rounded-full bg-white px-6 py-3 text-sm font-bold text-blue-900">Send Enquiry <ArrowRight size={17}/></Link></div></div></section>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify({"@context":"https://schema.org","@graph":[{"@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":baseUrl},{"@type":"ListItem","position":2,"name":"Prayagraj Yatra Package","item":`${baseUrl}/prayagraj-yatra-package`}]},{"@type":"Service","name":"Prayagraj Yatra Packages","serviceType":"Prayagraj Yatra Package","url":`${baseUrl}/prayagraj-yatra-package`} ]})}} />
  </main>;
}
