// AUTO-GENERATED by scripts/generate-package-media.mjs. Do not edit manually.
export const packageMedia: Record<string, string[]> = {
  "andaman-nicobar/andaman-grand-island-tour": [
    "/images/packages/andaman-nicobar/andaman-grand-island-tour/gallery1.avif",
    "/images/packages/andaman-nicobar/andaman-grand-island-tour/gallery2.avif",
    "/images/packages/andaman-nicobar/andaman-grand-island-tour/gallery3.avif",
    "/images/packages/andaman-nicobar/andaman-grand-island-tour/hero.avif"
  ],
  "andaman-nicobar/andaman-havelock-neil-island": [
    "/images/packages/andaman-nicobar/andaman-havelock-neil-island/gallery1.avif",
    "/images/packages/andaman-nicobar/andaman-havelock-neil-island/gallery2.avif",
    "/images/packages/andaman-nicobar/andaman-havelock-neil-island/gallery3.avif",
    "/images/packages/andaman-nicobar/andaman-havelock-neil-island/hero.avif"
  ],
  "andaman-nicobar/andaman-honeymoon": [
    "/images/packages/andaman-nicobar/andaman-honeymoon/gallery1.avif",
    "/images/packages/andaman-nicobar/andaman-honeymoon/gallery2.avif",
    "/images/packages/andaman-nicobar/andaman-honeymoon/gallery3.avif",
    "/images/packages/andaman-nicobar/andaman-honeymoon/hero.avif"
  ],
  "andaman-nicobar/andaman-port-blair-havelock": [
    "/images/packages/andaman-nicobar/andaman-port-blair-havelock/gallery1.avif",
    "/images/packages/andaman-nicobar/andaman-port-blair-havelock/gallery2.avif",
    "/images/packages/andaman-nicobar/andaman-port-blair-havelock/gallery3.avif",
    "/images/packages/andaman-nicobar/andaman-port-blair-havelock/hero.avif"
  ],
  "andhra-pradesh/tirupati-tirumala": [
    "/images/packages/andhra-pradesh/tirupati-tirumala/gallery1.avif",
    "/images/packages/andhra-pradesh/tirupati-tirumala/gallery2.avif",
    "/images/packages/andhra-pradesh/tirupati-tirumala/gallery3.avif",
    "/images/packages/andhra-pradesh/tirupati-tirumala/hero.avif"
  ],
  "andhra-pradesh/vijayawada-amaravati": [
    "/images/packages/andhra-pradesh/vijayawada-amaravati/gallery1.avif",
    "/images/packages/andhra-pradesh/vijayawada-amaravati/gallery2.avif",
    "/images/packages/andhra-pradesh/vijayawada-amaravati/gallery3.avif",
    "/images/packages/andhra-pradesh/vijayawada-amaravati/hero.avif"
  ],
  "andhra-pradesh/vizag-araku-valley": [
    "/images/packages/andhra-pradesh/vizag-araku-valley/gallery1.avif",
    "/images/packages/andhra-pradesh/vizag-araku-valley/gallery2.avif",
    "/images/packages/andhra-pradesh/vizag-araku-valley/gallery3.avif",
    "/images/packages/andhra-pradesh/vizag-araku-valley/hero.avif"
  ],
  "arunachal-pradesh/tawang-bomdila": [
    "/images/packages/arunachal-pradesh/tawang-bomdila/gallery1.avif",
    "/images/packages/arunachal-pradesh/tawang-bomdila/gallery2.avif",
    "/images/packages/arunachal-pradesh/tawang-bomdila/gallery3.avif",
    "/images/packages/arunachal-pradesh/tawang-bomdila/hero.avif"
  ],
  "arunachal-pradesh/ziro-valley-itinerary": [
    "/images/packages/arunachal-pradesh/ziro-valley-itinerary/gallery1.avif",
    "/images/packages/arunachal-pradesh/ziro-valley-itinerary/gallery2.avif",
    "/images/packages/arunachal-pradesh/ziro-valley-itinerary/gallery3.avif",
    "/images/packages/arunachal-pradesh/ziro-valley-itinerary/hero.avif"
  ],
  "assam/guwahati-shillong-cherrapunji": [
    "/images/packages/assam/guwahati-shillong-cherrapunji/gallery1.jpg",
    "/images/packages/assam/guwahati-shillong-cherrapunji/gallery2.jpg",
    "/images/packages/assam/guwahati-shillong-cherrapunji/gallery3.jpg",
    "/images/packages/assam/guwahati-shillong-cherrapunji/gallery4.jpg",
    "/images/packages/assam/guwahati-shillong-cherrapunji/gallery5.jpg",
    "/images/packages/assam/guwahati-shillong-cherrapunji/hero.jpg"
  ],
  "assam/kaziranga-shillong": [
    "/images/packages/assam/kaziranga-shillong/gallery1.jpg",
    "/images/packages/assam/kaziranga-shillong/gallery2.jpg",
    "/images/packages/assam/kaziranga-shillong/gallery3.jpg",
    "/images/packages/assam/kaziranga-shillong/gallery4.jpg",
    "/images/packages/assam/kaziranga-shillong/gallery5.jpg",
    "/images/packages/assam/kaziranga-shillong/hero.jpg"
  ],
  "bihar/bihar-buddhist-circuit": [
    "/images/packages/bihar/bihar-buddhist-circuit/gallery1.jpg",
    "/images/packages/bihar/bihar-buddhist-circuit/gallery2.jpg",
    "/images/packages/bihar/bihar-buddhist-circuit/gallery3.jpg",
    "/images/packages/bihar/bihar-buddhist-circuit/gallery4.jpg",
    "/images/packages/bihar/bihar-buddhist-circuit/gallery5.jpg",
    "/images/packages/bihar/bihar-buddhist-circuit/hero.jpg"
  ],
  "bihar/bodhgaya-rajgir-nalanda": [
    "/images/packages/bihar/bodhgaya-rajgir-nalanda/gallery1.jpg",
    "/images/packages/bihar/bodhgaya-rajgir-nalanda/gallery2.jpg",
    "/images/packages/bihar/bodhgaya-rajgir-nalanda/gallery3.jpg",
    "/images/packages/bihar/bodhgaya-rajgir-nalanda/gallery4.jpg",
    "/images/packages/bihar/bodhgaya-rajgir-nalanda/gallery5.jpg",
    "/images/packages/bihar/bodhgaya-rajgir-nalanda/hero.jpg"
  ],
  "bihar/patna-gaya-bihar-tour": [
    "/images/packages/bihar/patna-gaya-bihar-tour/gallery1.jpg",
    "/images/packages/bihar/patna-gaya-bihar-tour/gallery2.jpg",
    "/images/packages/bihar/patna-gaya-bihar-tour/gallery3.jpg",
    "/images/packages/bihar/patna-gaya-bihar-tour/gallery4.jpg",
    "/images/packages/bihar/patna-gaya-bihar-tour/gallery5.jpg",
    "/images/packages/bihar/patna-gaya-bihar-tour/hero.jpg"
  ],
  "chandigarh/chandigarh-city-tour": [
    "/images/packages/chandigarh/chandigarh-city-tour/gallery1.jpg",
    "/images/packages/chandigarh/chandigarh-city-tour/gallery2.jpg",
    "/images/packages/chandigarh/chandigarh-city-tour/gallery3.jpg",
    "/images/packages/chandigarh/chandigarh-city-tour/gallery4.jpg",
    "/images/packages/chandigarh/chandigarh-city-tour/gallery5.jpg",
    "/images/packages/chandigarh/chandigarh-city-tour/hero.jpg"
  ],
  "chandigarh/chandigarh-shimla": [
    "/images/packages/chandigarh/chandigarh-shimla/gallery1.avif",
    "/images/packages/chandigarh/chandigarh-shimla/gallery2.avif",
    "/images/packages/chandigarh/chandigarh-shimla/gallery3.avif",
    "/images/packages/chandigarh/chandigarh-shimla/hero.avif"
  ],
  "delhi/delhi-agra-jaipur": [
    "/images/packages/delhi/delhi-agra-jaipur/gallery1.avif",
    "/images/packages/delhi/delhi-agra-jaipur/gallery2.avif",
    "/images/packages/delhi/delhi-agra-jaipur/gallery3.avif",
    "/images/packages/delhi/delhi-agra-jaipur/hero.avif"
  ],
  "delhi/delhi-city-heritage": [
    "/images/packages/delhi/delhi-city-heritage/gallery1.jpg",
    "/images/packages/delhi/delhi-city-heritage/gallery2.jpg",
    "/images/packages/delhi/delhi-city-heritage/gallery3.jpg",
    "/images/packages/delhi/delhi-city-heritage/gallery4.jpg",
    "/images/packages/delhi/delhi-city-heritage/gallery5.jpg",
    "/images/packages/delhi/delhi-city-heritage/hero.jpg"
  ],
  "delhi/delhi-mathura-vrindavan": [
    "/images/packages/delhi/delhi-mathura-vrindavan/gallery1.avif",
    "/images/packages/delhi/delhi-mathura-vrindavan/gallery2.avif",
    "/images/packages/delhi/delhi-mathura-vrindavan/gallery3.avif",
    "/images/packages/delhi/delhi-mathura-vrindavan/gallery4.jpg",
    "/images/packages/delhi/delhi-mathura-vrindavan/hero.avif"
  ],
  "goa/corporate-goa-offsite": [
    "/images/packages/goa/corporate-goa-offsite/gallery1.avif",
    "/images/packages/goa/corporate-goa-offsite/gallery2.avif",
    "/images/packages/goa/corporate-goa-offsite/gallery3.avif",
    "/images/packages/goa/corporate-goa-offsite/hero.avif"
  ],
  "goa/goa-classic-holiday": [
    "/images/packages/goa/goa-classic-holiday/gallery1.avif",
    "/images/packages/goa/goa-classic-holiday/gallery2.avif",
    "/images/packages/goa/goa-classic-holiday/gallery3.avif",
    "/images/packages/goa/goa-classic-holiday/gallery4.jpg",
    "/images/packages/goa/goa-classic-holiday/gallery5.jpg",
    "/images/packages/goa/goa-classic-holiday/hero.avif"
  ],
  "goa/goa-honeymoon": [
    "/images/packages/goa/goa-honeymoon/gallery1.avif",
    "/images/packages/goa/goa-honeymoon/gallery2.avif",
    "/images/packages/goa/goa-honeymoon/gallery3.avif",
    "/images/packages/goa/goa-honeymoon/hero.avif"
  ],
  "gujarat/dwarka-somnath": [
    "/images/packages/gujarat/dwarka-somnath/gallery1.avif",
    "/images/packages/gujarat/dwarka-somnath/gallery2.avif",
    "/images/packages/gujarat/dwarka-somnath/gallery3.avif",
    "/images/packages/gujarat/dwarka-somnath/hero.avif"
  ],
  "gujarat/gir-national-park": [
    "/images/packages/gujarat/gir-national-park/gallery1.avif",
    "/images/packages/gujarat/gir-national-park/gallery2.avif",
    "/images/packages/gujarat/gir-national-park/gallery3.avif",
    "/images/packages/gujarat/gir-national-park/hero.avif"
  ],
  "gujarat/gujarat-grand-tour": [
    "/images/packages/gujarat/gujarat-grand-tour/gallery1.avif",
    "/images/packages/gujarat/gujarat-grand-tour/gallery2.avif",
    "/images/packages/gujarat/gujarat-grand-tour/gallery3.avif",
    "/images/packages/gujarat/gujarat-grand-tour/hero.avif"
  ],
  "gujarat/rann-utsav": [
    "/images/packages/gujarat/rann-utsav/gallery1.webp",
    "/images/packages/gujarat/rann-utsav/gallery2.webp",
    "/images/packages/gujarat/rann-utsav/gallery3.webp",
    "/images/packages/gujarat/rann-utsav/gallery4.jpg",
    "/images/packages/gujarat/rann-utsav/hero.jpg"
  ],
  "gujarat/saputara": [
    "/images/packages/gujarat/saputara/gallery1.jpg",
    "/images/packages/gujarat/saputara/gallery2.jpg",
    "/images/packages/gujarat/saputara/gallery3.jpg",
    "/images/packages/gujarat/saputara/gallery4.jpg",
    "/images/packages/gujarat/saputara/gallery5.jpg",
    "/images/packages/gujarat/saputara/hero.jpg"
  ],
  "gujarat/statue-of-unity": [
    "/images/packages/gujarat/statue-of-unity/gallery1.avif",
    "/images/packages/gujarat/statue-of-unity/gallery2.avif",
    "/images/packages/gujarat/statue-of-unity/gallery3.avif",
    "/images/packages/gujarat/statue-of-unity/gallery4.jpg",
    "/images/packages/gujarat/statue-of-unity/hero.avif"
  ],
  "himachal-pradesh/corporate-manali-offsite": [
    "/images/packages/himachal-pradesh/corporate-manali-offsite/gallery1.avif",
    "/images/packages/himachal-pradesh/corporate-manali-offsite/gallery2.avif",
    "/images/packages/himachal-pradesh/corporate-manali-offsite/gallery3.avif",
    "/images/packages/himachal-pradesh/corporate-manali-offsite/hero.avif",
    "/images/packages/himachal-pradesh/corporate-manali-offsite/hero.webp"
  ],
  "himachal-pradesh/corporate-shimla-kufri-offsite": [
    "/images/packages/himachal-pradesh/corporate-shimla-kufri-offsite/gallery1.avif",
    "/images/packages/himachal-pradesh/corporate-shimla-kufri-offsite/gallery2.avif",
    "/images/packages/himachal-pradesh/corporate-shimla-kufri-offsite/gallery3.avif",
    "/images/packages/himachal-pradesh/corporate-shimla-kufri-offsite/hero.avif",
    "/images/packages/himachal-pradesh/corporate-shimla-kufri-offsite/hero.webp"
  ],
  "himachal-pradesh/dharamshala-dalhousie-khajjiar": [
    "/images/packages/himachal-pradesh/dharamshala-dalhousie-khajjiar/gallery1.avif",
    "/images/packages/himachal-pradesh/dharamshala-dalhousie-khajjiar/gallery2.avif",
    "/images/packages/himachal-pradesh/dharamshala-dalhousie-khajjiar/gallery3.avif",
    "/images/packages/himachal-pradesh/dharamshala-dalhousie-khajjiar/hero.avif",
    "/images/packages/himachal-pradesh/dharamshala-dalhousie-khajjiar/hero.webp"
  ],
  "himachal-pradesh/kasol-manali": [
    "/images/packages/himachal-pradesh/kasol-manali/gallery1.avif",
    "/images/packages/himachal-pradesh/kasol-manali/gallery2.avif",
    "/images/packages/himachal-pradesh/kasol-manali/gallery3.avif",
    "/images/packages/himachal-pradesh/kasol-manali/hero.avif",
    "/images/packages/himachal-pradesh/kasol-manali/hero.webp"
  ],
  "himachal-pradesh/kasol-manikaran-2n3d": [
    "/images/packages/himachal-pradesh/kasol-manikaran-2n3d/gallery1.avif",
    "/images/packages/himachal-pradesh/kasol-manikaran-2n3d/gallery2.avif",
    "/images/packages/himachal-pradesh/kasol-manikaran-2n3d/gallery3.avif",
    "/images/packages/himachal-pradesh/kasol-manikaran-2n3d/hero.avif",
    "/images/packages/himachal-pradesh/kasol-manikaran-2n3d/hero.webp"
  ],
  "himachal-pradesh/kasol-tosh-parvati-valley": [
    "/images/packages/himachal-pradesh/kasol-tosh-parvati-valley/gallery1.avif",
    "/images/packages/himachal-pradesh/kasol-tosh-parvati-valley/gallery2.avif",
    "/images/packages/himachal-pradesh/kasol-tosh-parvati-valley/gallery3.avif",
    "/images/packages/himachal-pradesh/kasol-tosh-parvati-valley/hero.avif",
    "/images/packages/himachal-pradesh/kasol-tosh-parvati-valley/hero.webp"
  ],
  "himachal-pradesh/manali-honeymoon": [
    "/images/packages/himachal-pradesh/manali-honeymoon/gallery1.avif",
    "/images/packages/himachal-pradesh/manali-honeymoon/gallery2.avif",
    "/images/packages/himachal-pradesh/manali-honeymoon/gallery3.avif",
    "/images/packages/himachal-pradesh/manali-honeymoon/hero.avif",
    "/images/packages/himachal-pradesh/manali-honeymoon/hero.webp"
  ],
  "himachal-pradesh/manali-solang-valley": [
    "/images/packages/himachal-pradesh/manali-solang-valley/gallery1.avif",
    "/images/packages/himachal-pradesh/manali-solang-valley/gallery2.avif",
    "/images/packages/himachal-pradesh/manali-solang-valley/gallery3.avif",
    "/images/packages/himachal-pradesh/manali-solang-valley/hero.avif",
    "/images/packages/himachal-pradesh/manali-solang-valley/hero.webp"
  ],
  "himachal-pradesh/shimla-manali": [
    "/images/packages/himachal-pradesh/shimla-manali/gallery1.avif",
    "/images/packages/himachal-pradesh/shimla-manali/gallery2.avif",
    "/images/packages/himachal-pradesh/shimla-manali/gallery3.avif",
    "/images/packages/himachal-pradesh/shimla-manali/hero.avif",
    "/images/packages/himachal-pradesh/shimla-manali/hero.webp"
  ],
  "himachal-pradesh/spiti-valley-road-trip": [
    "/images/packages/himachal-pradesh/spiti-valley-road-trip/gallery1.avif",
    "/images/packages/himachal-pradesh/spiti-valley-road-trip/gallery2.avif",
    "/images/packages/himachal-pradesh/spiti-valley-road-trip/gallery3.avif",
    "/images/packages/himachal-pradesh/spiti-valley-road-trip/hero.avif",
    "/images/packages/himachal-pradesh/spiti-valley-road-trip/hero.webp"
  ],
  "himachal-pradesh/tirthan-valley-jibhi": [
    "/images/packages/himachal-pradesh/tirthan-valley-jibhi/gallery1.avif",
    "/images/packages/himachal-pradesh/tirthan-valley-jibhi/gallery2.avif",
    "/images/packages/himachal-pradesh/tirthan-valley-jibhi/gallery3.avif",
    "/images/packages/himachal-pradesh/tirthan-valley-jibhi/hero.avif",
    "/images/packages/himachal-pradesh/tirthan-valley-jibhi/hero.webp"
  ],
  "jammu-kashmir": [
    "/images/packages/jammu-kashmir/gallery1.avif",
    "/images/packages/jammu-kashmir/gallery2.avif",
    "/images/packages/jammu-kashmir/gallery3.avif",
    "/images/packages/jammu-kashmir/hero.avif"
  ],
  "jharkhand/deoghar-baidyanath": [
    "/images/packages/jharkhand/deoghar-baidyanath/gallery1.jpg",
    "/images/packages/jharkhand/deoghar-baidyanath/gallery2.jpg",
    "/images/packages/jharkhand/deoghar-baidyanath/gallery3.jpg",
    "/images/packages/jharkhand/deoghar-baidyanath/gallery4.jpg",
    "/images/packages/jharkhand/deoghar-baidyanath/gallery5.jpg",
    "/images/packages/jharkhand/deoghar-baidyanath/hero.jpg"
  ],
  "jharkhand/ranchi-netarhat-waterfalls": [
    "/images/packages/jharkhand/ranchi-netarhat-waterfalls/gallery1.jpg",
    "/images/packages/jharkhand/ranchi-netarhat-waterfalls/gallery2.jpg",
    "/images/packages/jharkhand/ranchi-netarhat-waterfalls/gallery3.jpg",
    "/images/packages/jharkhand/ranchi-netarhat-waterfalls/gallery4.jpg",
    "/images/packages/jharkhand/ranchi-netarhat-waterfalls/gallery5.jpg",
    "/images/packages/jharkhand/ranchi-netarhat-waterfalls/hero.jpg"
  ],
  "karnataka/bangalore-mysore-coorg": [
    "/images/packages/karnataka/bangalore-mysore-coorg/gallery1.avif",
    "/images/packages/karnataka/bangalore-mysore-coorg/gallery2.avif",
    "/images/packages/karnataka/bangalore-mysore-coorg/gallery3.avif",
    "/images/packages/karnataka/bangalore-mysore-coorg/hero.avif"
  ],
  "karnataka/hampi-heritage": [
    "/images/packages/karnataka/hampi-heritage/gallery1.jpg",
    "/images/packages/karnataka/hampi-heritage/gallery2.jpg",
    "/images/packages/karnataka/hampi-heritage/gallery3.jpg",
    "/images/packages/karnataka/hampi-heritage/gallery4.jpg",
    "/images/packages/karnataka/hampi-heritage/gallery5.jpg",
    "/images/packages/karnataka/hampi-heritage/hero.jpg"
  ],
  "kashmir/amarnath-yatra-kashmir": [
    "/images/packages/kashmir/amarnath-yatra-kashmir/gallery1.avif",
    "/images/packages/kashmir/amarnath-yatra-kashmir/gallery2.avif",
    "/images/packages/kashmir/amarnath-yatra-kashmir/gallery3.avif",
    "/images/packages/kashmir/amarnath-yatra-kashmir/hero.avif"
  ],
  "kashmir/corporate-kashmir-srinagar-gulmarg": [
    "/images/packages/kashmir/corporate-kashmir-srinagar-gulmarg/gallery1.avif",
    "/images/packages/kashmir/corporate-kashmir-srinagar-gulmarg/gallery2.avif",
    "/images/packages/kashmir/corporate-kashmir-srinagar-gulmarg/gallery3.avif",
    "/images/packages/kashmir/corporate-kashmir-srinagar-gulmarg/hero.avif"
  ],
  "kashmir/kashmir-classic-srinagar-gulmarg-pahalgam-sonmarg": [
    "/images/packages/kashmir/kashmir-classic-srinagar-gulmarg-pahalgam-sonmarg/gallery1.avif",
    "/images/packages/kashmir/kashmir-classic-srinagar-gulmarg-pahalgam-sonmarg/gallery2.avif",
    "/images/packages/kashmir/kashmir-classic-srinagar-gulmarg-pahalgam-sonmarg/gallery3.avif",
    "/images/packages/kashmir/kashmir-classic-srinagar-gulmarg-pahalgam-sonmarg/hero.avif"
  ],
  "kashmir/kashmir-grand-tour": [
    "/images/packages/kashmir/kashmir-grand-tour/gallery1.avif",
    "/images/packages/kashmir/kashmir-grand-tour/gallery2.avif",
    "/images/packages/kashmir/kashmir-grand-tour/gallery3.avif",
    "/images/packages/kashmir/kashmir-grand-tour/hero.avif"
  ],
  "kashmir/kashmir-honeymoon": [
    "/images/packages/kashmir/kashmir-honeymoon/gallery1.avif",
    "/images/packages/kashmir/kashmir-honeymoon/gallery2.avif",
    "/images/packages/kashmir/kashmir-honeymoon/gallery3.avif",
    "/images/packages/kashmir/kashmir-honeymoon/hero.avif"
  ],
  "kashmir/kashmir-offbeat-gurez-doodhpathri": [
    "/images/packages/kashmir/kashmir-offbeat-gurez-doodhpathri/gallery1.avif",
    "/images/packages/kashmir/kashmir-offbeat-gurez-doodhpathri/gallery2.avif",
    "/images/packages/kashmir/kashmir-offbeat-gurez-doodhpathri/gallery3.avif",
    "/images/packages/kashmir/kashmir-offbeat-gurez-doodhpathri/hero.avif"
  ],
  "kashmir/kashmir-tulip-season": [
    "/images/packages/kashmir/kashmir-tulip-season/gallery1.avif",
    "/images/packages/kashmir/kashmir-tulip-season/gallery2.avif",
    "/images/packages/kashmir/kashmir-tulip-season/gallery3.avif",
    "/images/packages/kashmir/kashmir-tulip-season/hero.avif"
  ],
  "kashmir/kashmir-winter-snow": [
    "/images/packages/kashmir/kashmir-winter-snow/gallery1.avif",
    "/images/packages/kashmir/kashmir-winter-snow/gallery2.avif",
    "/images/packages/kashmir/kashmir-winter-snow/gallery3.avif",
    "/images/packages/kashmir/kashmir-winter-snow/hero.avif"
  ],
  "kashmir/srinagar-gulmarg-pahalgam": [
    "/images/packages/kashmir/srinagar-gulmarg-pahalgam/gallery1.avif",
    "/images/packages/kashmir/srinagar-gulmarg-pahalgam/gallery2.avif",
    "/images/packages/kashmir/srinagar-gulmarg-pahalgam/gallery3.avif",
    "/images/packages/kashmir/srinagar-gulmarg-pahalgam/hero.avif"
  ],
  "kerala/corporate-kerala-kochi-munnar": [
    "/images/packages/kerala/corporate-kerala-kochi-munnar/gallery1.avif",
    "/images/packages/kerala/corporate-kerala-kochi-munnar/gallery2.avif",
    "/images/packages/kerala/corporate-kerala-kochi-munnar/gallery3.avif",
    "/images/packages/kerala/corporate-kerala-kochi-munnar/gallery5.jpg",
    "/images/packages/kerala/corporate-kerala-kochi-munnar/hero.avif"
  ],
  "kerala/kerala-grand-tour": [
    "/images/packages/kerala/kerala-grand-tour/gallery1.avif",
    "/images/packages/kerala/kerala-grand-tour/gallery2.avif",
    "/images/packages/kerala/kerala-grand-tour/gallery3.avif",
    "/images/packages/kerala/kerala-grand-tour/gallery4.jpg",
    "/images/packages/kerala/kerala-grand-tour/hero.avif"
  ],
  "kerala/kerala-honeymoon": [
    "/images/packages/kerala/kerala-honeymoon/gallery1.avif",
    "/images/packages/kerala/kerala-honeymoon/gallery2.avif",
    "/images/packages/kerala/kerala-honeymoon/gallery2.webp",
    "/images/packages/kerala/kerala-honeymoon/gallery4.avif",
    "/images/packages/kerala/kerala-honeymoon/hero.avif"
  ],
  "kerala/kerala-munnar-thekkady-alleppey": [
    "/images/packages/kerala/kerala-munnar-thekkady-alleppey/gallery1.avif",
    "/images/packages/kerala/kerala-munnar-thekkady-alleppey/gallery2.avif",
    "/images/packages/kerala/kerala-munnar-thekkady-alleppey/gallery3.avif",
    "/images/packages/kerala/kerala-munnar-thekkady-alleppey/gallery4.jpg",
    "/images/packages/kerala/kerala-munnar-thekkady-alleppey/hero.avif"
  ],
  "ladakh/corporate-ladakh-offsite": [
    "/images/packages/ladakh/corporate-ladakh-offsite/gallery1.avif",
    "/images/packages/ladakh/corporate-ladakh-offsite/gallery2.avif",
    "/images/packages/ladakh/corporate-ladakh-offsite/gallery3.avif",
    "/images/packages/ladakh/corporate-ladakh-offsite/hero.avif"
  ],
  "ladakh/ladakh-complete-road-trip": [
    "/images/packages/ladakh/ladakh-complete-road-trip/gallery1.avif",
    "/images/packages/ladakh/ladakh-complete-road-trip/gallery2.avif",
    "/images/packages/ladakh/ladakh-complete-road-trip/gallery3.avif",
    "/images/packages/ladakh/ladakh-complete-road-trip/hero.avif"
  ],
  "ladakh/ladakh-grand-tour": [
    "/images/packages/ladakh/ladakh-grand-tour/gallery1.avif",
    "/images/packages/ladakh/ladakh-grand-tour/gallery2.avif",
    "/images/packages/ladakh/ladakh-grand-tour/gallery3.avif",
    "/images/packages/ladakh/ladakh-grand-tour/hero.avif"
  ],
  "ladakh/ladakh-honeymoon": [
    "/images/packages/ladakh/ladakh-honeymoon/gallery1.avif",
    "/images/packages/ladakh/ladakh-honeymoon/gallery2.avif",
    "/images/packages/ladakh/ladakh-honeymoon/gallery3.avif",
    "/images/packages/ladakh/ladakh-honeymoon/hero.avif"
  ],
  "ladakh/leh-nubra-pangong-classic": [
    "/images/packages/ladakh/leh-nubra-pangong-classic/gallery1.avif",
    "/images/packages/ladakh/leh-nubra-pangong-classic/gallery2.avif",
    "/images/packages/ladakh/leh-nubra-pangong-classic/gallery3.avif",
    "/images/packages/ladakh/leh-nubra-pangong-classic/hero.avif"
  ],
  "madhya-pradesh/kanha-bandhavgarh": [
    "/images/packages/madhya-pradesh/kanha-bandhavgarh/gallery1.avif",
    "/images/packages/madhya-pradesh/kanha-bandhavgarh/gallery2.avif",
    "/images/packages/madhya-pradesh/kanha-bandhavgarh/gallery3.avif",
    "/images/packages/madhya-pradesh/kanha-bandhavgarh/gallery4.jpg",
    "/images/packages/madhya-pradesh/kanha-bandhavgarh/hero.avif"
  ],
  "madhya-pradesh/khajuraho-orchha": [
    "/images/packages/madhya-pradesh/khajuraho-orchha/gallery1.jpg",
    "/images/packages/madhya-pradesh/khajuraho-orchha/gallery2.jpg",
    "/images/packages/madhya-pradesh/khajuraho-orchha/gallery3.jpg",
    "/images/packages/madhya-pradesh/khajuraho-orchha/gallery4.jpg",
    "/images/packages/madhya-pradesh/khajuraho-orchha/gallery5.jpg",
    "/images/packages/madhya-pradesh/khajuraho-orchha/hero.avif"
  ],
  "madhya-pradesh/ujjain-omkareshwar": [
    "/images/packages/madhya-pradesh/ujjain-omkareshwar/gallery1.jpg",
    "/images/packages/madhya-pradesh/ujjain-omkareshwar/gallery2.jpg",
    "/images/packages/madhya-pradesh/ujjain-omkareshwar/gallery3.webp",
    "/images/packages/madhya-pradesh/ujjain-omkareshwar/gallery4.jpg",
    "/images/packages/madhya-pradesh/ujjain-omkareshwar/gallery5.jpg",
    "/images/packages/madhya-pradesh/ujjain-omkareshwar/hero.jpg"
  ],
  "maharashtra/ajanta-ellora-aurangabad": [
    "/images/packages/maharashtra/ajanta-ellora-aurangabad/gallery1.jpg",
    "/images/packages/maharashtra/ajanta-ellora-aurangabad/gallery2.jpg",
    "/images/packages/maharashtra/ajanta-ellora-aurangabad/gallery3.jpg",
    "/images/packages/maharashtra/ajanta-ellora-aurangabad/gallery4.jpg",
    "/images/packages/maharashtra/ajanta-ellora-aurangabad/gallery5.jpg",
    "/images/packages/maharashtra/ajanta-ellora-aurangabad/hero.jpg"
  ],
  "maharashtra/lonavala-khandala-weekend": [
    "/images/packages/maharashtra/lonavala-khandala-weekend/gallery1.avif",
    "/images/packages/maharashtra/lonavala-khandala-weekend/gallery2.avif",
    "/images/packages/maharashtra/lonavala-khandala-weekend/gallery3.jpg",
    "/images/packages/maharashtra/lonavala-khandala-weekend/gallery4.jpg",
    "/images/packages/maharashtra/lonavala-khandala-weekend/hero.avif"
  ],
  "maharashtra/mumbai-city-tour": [
    "/images/packages/maharashtra/mumbai-city-tour/gallery1.avif",
    "/images/packages/maharashtra/mumbai-city-tour/gallery2.avif",
    "/images/packages/maharashtra/mumbai-city-tour/gallery3.avif",
    "/images/packages/maharashtra/mumbai-city-tour/hero.avif"
  ],
  "maharashtra/shirdi-nashik": [
    "/images/packages/maharashtra/shirdi-nashik/gallery1.jpg",
    "/images/packages/maharashtra/shirdi-nashik/gallery2.jpg",
    "/images/packages/maharashtra/shirdi-nashik/gallery3.jpg",
    "/images/packages/maharashtra/shirdi-nashik/gallery4.jpg",
    "/images/packages/maharashtra/shirdi-nashik/gallery5.jpg",
    "/images/packages/maharashtra/shirdi-nashik/hero.jpg"
  ],
  "meghalaya/guwahati-shillong-cherrapunji": [
    "/images/packages/meghalaya/guwahati-shillong-cherrapunji/gallery1.jpg",
    "/images/packages/meghalaya/guwahati-shillong-cherrapunji/gallery2.avif",
    "/images/packages/meghalaya/guwahati-shillong-cherrapunji/gallery3.avif",
    "/images/packages/meghalaya/guwahati-shillong-cherrapunji/gallery4.jpg",
    "/images/packages/meghalaya/guwahati-shillong-cherrapunji/hero.jpg"
  ],
  "punjab/amritsar-anandpur-sahib": [
    "/images/packages/punjab/amritsar-anandpur-sahib/gallery1.jpg",
    "/images/packages/punjab/amritsar-anandpur-sahib/gallery2.jpg",
    "/images/packages/punjab/amritsar-anandpur-sahib/gallery3.jpg",
    "/images/packages/punjab/amritsar-anandpur-sahib/gallery4.jpg",
    "/images/packages/punjab/amritsar-anandpur-sahib/gallery5.jpg",
    "/images/packages/punjab/amritsar-anandpur-sahib/hero.jpg"
  ],
  "punjab/amritsar-golden-temple-wagah": [
    "/images/packages/punjab/amritsar-golden-temple-wagah/gallery1.avif",
    "/images/packages/punjab/amritsar-golden-temple-wagah/gallery2.jpg",
    "/images/packages/punjab/amritsar-golden-temple-wagah/gallery3.jpg",
    "/images/packages/punjab/amritsar-golden-temple-wagah/hero.avif"
  ],
  "punjab/corporate-amritsar-retreat": [
    "/images/packages/punjab/corporate-amritsar-retreat/gallery1.jpg",
    "/images/packages/punjab/corporate-amritsar-retreat/gallery2.jpg",
    "/images/packages/punjab/corporate-amritsar-retreat/gallery3.jpg",
    "/images/packages/punjab/corporate-amritsar-retreat/gallery4.jpg",
    "/images/packages/punjab/corporate-amritsar-retreat/gallery5.jpg",
    "/images/packages/punjab/corporate-amritsar-retreat/hero.jpg"
  ],
  "rajasthan/jaipur-ajmer-pushkar": [
    "/images/packages/rajasthan/jaipur-ajmer-pushkar/gallery1.jpg",
    "/images/packages/rajasthan/jaipur-ajmer-pushkar/gallery2.jpg",
    "/images/packages/rajasthan/jaipur-ajmer-pushkar/gallery3.jpg",
    "/images/packages/rajasthan/jaipur-ajmer-pushkar/gallery4.jpg",
    "/images/packages/rajasthan/jaipur-ajmer-pushkar/gallery5.jpg",
    "/images/packages/rajasthan/jaipur-ajmer-pushkar/hero.jpg"
  ],
  "rajasthan/jaipur-heritage": [
    "/images/packages/rajasthan/jaipur-heritage/gallery1.jpg",
    "/images/packages/rajasthan/jaipur-heritage/gallery2.jpg",
    "/images/packages/rajasthan/jaipur-heritage/gallery3.jpg",
    "/images/packages/rajasthan/jaipur-heritage/gallery4.jpg",
    "/images/packages/rajasthan/jaipur-heritage/gallery5.jpg",
    "/images/packages/rajasthan/jaipur-heritage/hero.jpg"
  ],
  "rajasthan/jaipur-jodhpur-udaipur": [
    "/images/packages/rajasthan/jaipur-jodhpur-udaipur/gallery1.jpg",
    "/images/packages/rajasthan/jaipur-jodhpur-udaipur/gallery2.jpg",
    "/images/packages/rajasthan/jaipur-jodhpur-udaipur/gallery3.jpg",
    "/images/packages/rajasthan/jaipur-jodhpur-udaipur/gallery4.jpg",
    "/images/packages/rajasthan/jaipur-jodhpur-udaipur/gallery5.jpg",
    "/images/packages/rajasthan/jaipur-jodhpur-udaipur/hero.jpg"
  ],
  "rajasthan/jodhpur-jaisalmer": [
    "/images/packages/rajasthan/jodhpur-jaisalmer/gallery1.jpg",
    "/images/packages/rajasthan/jodhpur-jaisalmer/gallery2.jpg",
    "/images/packages/rajasthan/jodhpur-jaisalmer/gallery3.jpg",
    "/images/packages/rajasthan/jodhpur-jaisalmer/gallery4.jpg",
    "/images/packages/rajasthan/jodhpur-jaisalmer/gallery5.jpg",
    "/images/packages/rajasthan/jodhpur-jaisalmer/hero.jpg"
  ],
  "rajasthan/rajasthan-grand-tour": [
    "/images/packages/rajasthan/rajasthan-grand-tour/gallery1.jpg",
    "/images/packages/rajasthan/rajasthan-grand-tour/gallery2.jpg",
    "/images/packages/rajasthan/rajasthan-grand-tour/gallery3.jpg",
    "/images/packages/rajasthan/rajasthan-grand-tour/gallery4.jpg",
    "/images/packages/rajasthan/rajasthan-grand-tour/gallery5.jpg",
    "/images/packages/rajasthan/rajasthan-grand-tour/hero.jpg"
  ],
  "rajasthan/udaipur-mount-abu": [
    "/images/packages/rajasthan/udaipur-mount-abu/gallery1.jpg",
    "/images/packages/rajasthan/udaipur-mount-abu/gallery2.jpg",
    "/images/packages/rajasthan/udaipur-mount-abu/gallery3.jpg",
    "/images/packages/rajasthan/udaipur-mount-abu/gallery4.jpg",
    "/images/packages/rajasthan/udaipur-mount-abu/gallery5.jpg",
    "/images/packages/rajasthan/udaipur-mount-abu/hero.jpg"
  ],
  "sikkim/gangtok-lachen-lachung": [
    "/images/packages/sikkim/gangtok-lachen-lachung/gallery1.jpg",
    "/images/packages/sikkim/gangtok-lachen-lachung/gallery2.jpg",
    "/images/packages/sikkim/gangtok-lachen-lachung/gallery3.jpg",
    "/images/packages/sikkim/gangtok-lachen-lachung/gallery4.jpg",
    "/images/packages/sikkim/gangtok-lachen-lachung/gallery5.jpg",
    "/images/packages/sikkim/gangtok-lachen-lachung/hero.jpg"
  ],
  "sikkim/gangtok-tsomgo": [
    "/images/packages/sikkim/gangtok-tsomgo/gallery1.jpg",
    "/images/packages/sikkim/gangtok-tsomgo/gallery2.jpg",
    "/images/packages/sikkim/gangtok-tsomgo/gallery3.jpg",
    "/images/packages/sikkim/gangtok-tsomgo/gallery4.jpg",
    "/images/packages/sikkim/gangtok-tsomgo/gallery5.jpg",
    "/images/packages/sikkim/gangtok-tsomgo/hero.jpg"
  ],
  "tamil-nadu/madurai-rameswaram-kanyakumari": [
    "/images/packages/tamil-nadu/madurai-rameswaram-kanyakumari/gallery1.jpg",
    "/images/packages/tamil-nadu/madurai-rameswaram-kanyakumari/gallery2.jpg",
    "/images/packages/tamil-nadu/madurai-rameswaram-kanyakumari/gallery3.jpg",
    "/images/packages/tamil-nadu/madurai-rameswaram-kanyakumari/gallery4.jpg",
    "/images/packages/tamil-nadu/madurai-rameswaram-kanyakumari/gallery5.jpg",
    "/images/packages/tamil-nadu/madurai-rameswaram-kanyakumari/hero.jpg"
  ],
  "tamil-nadu/ooty-kodaikanal": [
    "/images/packages/tamil-nadu/ooty-kodaikanal/gallery1.jpg",
    "/images/packages/tamil-nadu/ooty-kodaikanal/gallery2.jpg",
    "/images/packages/tamil-nadu/ooty-kodaikanal/gallery3.jpg",
    "/images/packages/tamil-nadu/ooty-kodaikanal/gallery4.jpg",
    "/images/packages/tamil-nadu/ooty-kodaikanal/gallery5.jpg",
    "/images/packages/tamil-nadu/ooty-kodaikanal/hero.jpg"
  ],
  "tamil-nadu/tamil-nadu-temple-tour": [
    "/images/packages/tamil-nadu/tamil-nadu-temple-tour/gallery1.jpg",
    "/images/packages/tamil-nadu/tamil-nadu-temple-tour/gallery2.jpg",
    "/images/packages/tamil-nadu/tamil-nadu-temple-tour/gallery3.jpg",
    "/images/packages/tamil-nadu/tamil-nadu-temple-tour/gallery4.jpg",
    "/images/packages/tamil-nadu/tamil-nadu-temple-tour/gallery5.jpg",
    "/images/packages/tamil-nadu/tamil-nadu-temple-tour/hero.jpg"
  ],
  "uttar-pradesh/agra-taj-mahal-weekend": [
    "/images/packages/uttar-pradesh/agra-taj-mahal-weekend/gallery1.jpg",
    "/images/packages/uttar-pradesh/agra-taj-mahal-weekend/gallery2.jpg",
    "/images/packages/uttar-pradesh/agra-taj-mahal-weekend/gallery3.jpg",
    "/images/packages/uttar-pradesh/agra-taj-mahal-weekend/gallery4.jpg",
    "/images/packages/uttar-pradesh/agra-taj-mahal-weekend/hero.jpeg",
    "/images/packages/uttar-pradesh/agra-taj-mahal-weekend/hero.jpg"
  ],
  "uttar-pradesh/ayodhya-ram-mandir": [
    "/images/packages/uttar-pradesh/ayodhya-ram-mandir/gallery1.jpg",
    "/images/packages/uttar-pradesh/ayodhya-ram-mandir/gallery2.jpg",
    "/images/packages/uttar-pradesh/ayodhya-ram-mandir/gallery3.jpg",
    "/images/packages/uttar-pradesh/ayodhya-ram-mandir/gallery4.jpg",
    "/images/packages/uttar-pradesh/ayodhya-ram-mandir/hero.jpeg",
    "/images/packages/uttar-pradesh/ayodhya-ram-mandir/hero.jpg"
  ],
  "uttar-pradesh/buddhist-circuit-sarnath-kushinagar": [
    "/images/packages/uttar-pradesh/buddhist-circuit-sarnath-kushinagar/gallery1.jpg",
    "/images/packages/uttar-pradesh/buddhist-circuit-sarnath-kushinagar/gallery2.jpg",
    "/images/packages/uttar-pradesh/buddhist-circuit-sarnath-kushinagar/gallery3.jpg",
    "/images/packages/uttar-pradesh/buddhist-circuit-sarnath-kushinagar/gallery4.jpg",
    "/images/packages/uttar-pradesh/buddhist-circuit-sarnath-kushinagar/gallery5.jpg",
    "/images/packages/uttar-pradesh/buddhist-circuit-sarnath-kushinagar/gallery6.jpg",
    "/images/packages/uttar-pradesh/buddhist-circuit-sarnath-kushinagar/hero.jpg"
  ],
  "uttar-pradesh/corporate-agra-offsite": [
    "/images/packages/uttar-pradesh/corporate-agra-offsite/gallery1.jpg",
    "/images/packages/uttar-pradesh/corporate-agra-offsite/gallery2.jpg",
    "/images/packages/uttar-pradesh/corporate-agra-offsite/gallery3.jpg",
    "/images/packages/uttar-pradesh/corporate-agra-offsite/hero.jpg"
  ],
  "uttar-pradesh/corporate-mathura-vrindavan-retreat": [
    "/images/packages/uttar-pradesh/corporate-mathura-vrindavan-retreat/gallery1.jpg",
    "/images/packages/uttar-pradesh/corporate-mathura-vrindavan-retreat/gallery2.jpg",
    "/images/packages/uttar-pradesh/corporate-mathura-vrindavan-retreat/gallery3.jpg",
    "/images/packages/uttar-pradesh/corporate-mathura-vrindavan-retreat/hero.jpg"
  ],
  "uttar-pradesh/lucknow-nawabi-heritage": [
    "/images/packages/uttar-pradesh/lucknow-nawabi-heritage/gallery1.jpg",
    "/images/packages/uttar-pradesh/lucknow-nawabi-heritage/gallery2.jpg",
    "/images/packages/uttar-pradesh/lucknow-nawabi-heritage/gallery3.jpg",
    "/images/packages/uttar-pradesh/lucknow-nawabi-heritage/gallery4.jpg",
    "/images/packages/uttar-pradesh/lucknow-nawabi-heritage/hero.jpg"
  ],
  "uttar-pradesh/mathura-vrindavan-barsana": [
    "/images/packages/uttar-pradesh/mathura-vrindavan-barsana/hero.jpg"
  ],
  "uttar-pradesh/varanasi-kashi": [
    "/images/packages/uttar-pradesh/varanasi-kashi/gallery1.jpg",
    "/images/packages/uttar-pradesh/varanasi-kashi/gallery2.jpg",
    "/images/packages/uttar-pradesh/varanasi-kashi/gallery3.jpg",
    "/images/packages/uttar-pradesh/varanasi-kashi/gallery4.jpg",
    "/images/packages/uttar-pradesh/varanasi-kashi/hero.jpg"
  ],
  "uttar-pradesh/varanasi-prayagraj-ayodhya": [
    "/images/packages/uttar-pradesh/varanasi-prayagraj-ayodhya/gallery1.webp",
    "/images/packages/uttar-pradesh/varanasi-prayagraj-ayodhya/gallery2.jpg",
    "/images/packages/uttar-pradesh/varanasi-prayagraj-ayodhya/gallery3.jpg",
    "/images/packages/uttar-pradesh/varanasi-prayagraj-ayodhya/gallery4.jpg",
    "/images/packages/uttar-pradesh/varanasi-prayagraj-ayodhya/hero.jpg"
  ],
  "uttarakhand/badrinath-yatra": [
    "/images/packages/uttarakhand/badrinath-yatra/gallery1.jpg",
    "/images/packages/uttarakhand/badrinath-yatra/gallery2.jpg",
    "/images/packages/uttarakhand/badrinath-yatra/gallery3.jpg",
    "/images/packages/uttarakhand/badrinath-yatra/gallery4.jpg",
    "/images/packages/uttarakhand/badrinath-yatra/hero.jpg"
  ],
  "uttarakhand/char-dham-yatra": [
    "/images/packages/uttarakhand/char-dham-yatra/gallery1.jpg",
    "/images/packages/uttarakhand/char-dham-yatra/gallery2.jpg",
    "/images/packages/uttarakhand/char-dham-yatra/gallery3.jpg",
    "/images/packages/uttarakhand/char-dham-yatra/gallery4.jpg",
    "/images/packages/uttarakhand/char-dham-yatra/hero.jpg"
  ],
  "uttarakhand/chopta-tungnath": [
    "/images/packages/uttarakhand/chopta-tungnath/gallery1.jpg",
    "/images/packages/uttarakhand/chopta-tungnath/gallery2.jpg",
    "/images/packages/uttarakhand/chopta-tungnath/gallery3.jpg",
    "/images/packages/uttarakhand/chopta-tungnath/gallery4.jpg",
    "/images/packages/uttarakhand/chopta-tungnath/hero.jpg"
  ],
  "uttarakhand/haridwar-rishikesh-mussoorie": [
    "/images/packages/uttarakhand/haridwar-rishikesh-mussoorie/gallery1.jpg",
    "/images/packages/uttarakhand/haridwar-rishikesh-mussoorie/gallery2.jpg",
    "/images/packages/uttarakhand/haridwar-rishikesh-mussoorie/gallery3.jpg",
    "/images/packages/uttarakhand/haridwar-rishikesh-mussoorie/gallery4.jpg",
    "/images/packages/uttarakhand/haridwar-rishikesh-mussoorie/gallery5.jpg",
    "/images/packages/uttarakhand/haridwar-rishikesh-mussoorie/hero.jpg"
  ],
  "uttarakhand/jim-corbett-weekend": [
    "/images/packages/uttarakhand/jim-corbett-weekend/gallery1.jpg",
    "/images/packages/uttarakhand/jim-corbett-weekend/gallery2.jpg",
    "/images/packages/uttarakhand/jim-corbett-weekend/hero.jpg"
  ],
  "uttarakhand/kedarnath-badrinath-do-dham": [
    "/images/packages/uttarakhand/kedarnath-badrinath-do-dham/gallery1.jpg",
    "/images/packages/uttarakhand/kedarnath-badrinath-do-dham/gallery2.jpg",
    "/images/packages/uttarakhand/kedarnath-badrinath-do-dham/gallery3.jpg",
    "/images/packages/uttarakhand/kedarnath-badrinath-do-dham/gallery4.jpg",
    "/images/packages/uttarakhand/kedarnath-badrinath-do-dham/gallery5.jpg",
    "/images/packages/uttarakhand/kedarnath-badrinath-do-dham/hero.jpg"
  ],
  "uttarakhand/kedarnath-yatra": [
    "/images/packages/uttarakhand/kedarnath-yatra/gallery1.jpg",
    "/images/packages/uttarakhand/kedarnath-yatra/gallery2.jpg",
    "/images/packages/uttarakhand/kedarnath-yatra/hero.jpg"
  ],
  "uttarakhand/madhyamaheshwar-yatra": [
    "/images/packages/uttarakhand/madhyamaheshwar-yatra/gallery1.jpg",
    "/images/packages/uttarakhand/madhyamaheshwar-yatra/gallery2.jpg",
    "/images/packages/uttarakhand/madhyamaheshwar-yatra/hero.jpg"
  ],
  "uttarakhand/nainital-bhimtal-kainchi-dham": [
    "/images/packages/uttarakhand/nainital-bhimtal-kainchi-dham/gallery1.jpg",
    "/images/packages/uttarakhand/nainital-bhimtal-kainchi-dham/gallery2.jpg",
    "/images/packages/uttarakhand/nainital-bhimtal-kainchi-dham/hero.jpg"
  ],
  "west-bengal/darjeeling-kalimpong": [
    "/images/packages/west-bengal/darjeeling-kalimpong/gallery1.jpg",
    "/images/packages/west-bengal/darjeeling-kalimpong/gallery2.jpg",
    "/images/packages/west-bengal/darjeeling-kalimpong/gallery3.jpg",
    "/images/packages/west-bengal/darjeeling-kalimpong/gallery4.jpg",
    "/images/packages/west-bengal/darjeeling-kalimpong/hero.jpg"
  ],
  "west-bengal/sundarbans-wildlife": [
    "/images/packages/west-bengal/sundarbans-wildlife/gallery1.jpg",
    "/images/packages/west-bengal/sundarbans-wildlife/gallery2.jpg",
    "/images/packages/west-bengal/sundarbans-wildlife/gallery3.jpg",
    "/images/packages/west-bengal/sundarbans-wildlife/gallery4.jpg",
    "/images/packages/west-bengal/sundarbans-wildlife/hero.jpg"
  ],
  "multi-state/varanasi-ayodhya-prayagraj-gaya-bodh-gaya": [
    "/images/packages/uttar-pradesh/varanasi-prayagraj-ayodhya/gallery1.webp",
    "/images/packages/uttar-pradesh/varanasi-prayagraj-ayodhya/gallery2.jpg",
    "/images/packages/uttar-pradesh/varanasi-prayagraj-ayodhya/gallery3.jpg",
    "/images/packages/uttar-pradesh/varanasi-prayagraj-ayodhya/gallery4.jpg",
    "/images/packages/uttar-pradesh/varanasi-prayagraj-ayodhya/hero.jpg"
  ],
  "multi-state/varanasi-ayodhya-prayagraj-gaya-bodh-gaya-deoghar": [
    "/images/packages/bihar/bihar-buddhist-circuit/gallery1.jpg",
    "/images/packages/bihar/bihar-buddhist-circuit/gallery2.jpg",
    "/images/packages/bihar/bihar-buddhist-circuit/gallery3.jpg",
    "/images/packages/bihar/bihar-buddhist-circuit/gallery4.jpg",
    "/images/packages/bihar/bihar-buddhist-circuit/gallery5.jpg",
    "/images/packages/bihar/bihar-buddhist-circuit/hero.jpg"
  ],
  "multi-state/delhi-agra-jaipur-golden-triangle": [
    "/images/packages/delhi/delhi-agra-jaipur/gallery1.avif",
    "/images/packages/delhi/delhi-agra-jaipur/gallery2.avif",
    "/images/packages/delhi/delhi-agra-jaipur/gallery3.avif",
    "/images/packages/delhi/delhi-agra-jaipur/hero.avif"
  ]
};
