// AUTO-GENERATED by scripts/generate-package-media.mjs. Do not edit manually.
export const packageMedia: Record<string, string[]> = {
  "andhra-pradesh/tirupati-tirumala": [
    "/images/packages/andhra-pradesh/tirupati-tirumala/gallery1.avif",
    "/images/packages/andhra-pradesh/tirupati-tirumala/gallery2.avif",
    "/images/packages/andhra-pradesh/tirupati-tirumala/gallery3.avif",
    "/images/packages/andhra-pradesh/tirupati-tirumala/hero.avif"
  ],
  "andhra-pradesh/vijayawada-amaravati": [
    "/images/packages/andhra-pradesh/vijayawada-amaravati/gallery1.avif",
    "/images/packages/andhra-pradesh/vijayawada-amaravati/gallery2.avif",
    "/images/packages/andhra-pradesh/vijayawada-amaravati/gallery3.avif",
    "/images/packages/andhra-pradesh/vijayawada-amaravati/hero.avif"
  ],
  "andhra-pradesh/vizag-araku-valley": [
    "/images/packages/andhra-pradesh/vizag-araku-valley/gallery1.avif",
    "/images/packages/andhra-pradesh/vizag-araku-valley/gallery2.avif",
    "/images/packages/andhra-pradesh/vizag-araku-valley/gallery3.avif",
    "/images/packages/andhra-pradesh/vizag-araku-valley/hero.avif"
  ],
  "assam/guwahati-shillong-cherrapunji": [
    "/images/packages/assam/guwahati-shillong-cherrapunji/gallery1.jpg",
    "/images/packages/assam/guwahati-shillong-cherrapunji/gallery2.jpg",
    "/images/packages/assam/guwahati-shillong-cherrapunji/gallery3.jpg",
    "/images/packages/assam/guwahati-shillong-cherrapunji/gallery4.jpg",
    "/images/packages/assam/guwahati-shillong-cherrapunji/gallery5.jpg",
    "/images/packages/assam/guwahati-shillong-cherrapunji/hero.jpg"
  ],
  "assam/kaziranga-shillong": [
    "/images/packages/assam/kaziranga-shillong/gallery1.jpg",
    "/images/packages/assam/kaziranga-shillong/gallery2.jpg",
    "/images/packages/assam/kaziranga-shillong/gallery3.jpg",
    "/images/packages/assam/kaziranga-shillong/gallery4.jpg",
    "/images/packages/assam/kaziranga-shillong/gallery5.jpg",
    "/images/packages/assam/kaziranga-shillong/hero.jpg"
  ],
  "gujarat/dwarka-somnath": [
    "/images/packages/gujarat/dwarka-somnath/hero.jpg"
  ],
  "gujarat/gir-national-park": [
    "/images/packages/gujarat/gir-national-park/gir-national-park.jpg"
  ],
  "gujarat/rann-utsav": [
    "/images/packages/gujarat/rann-utsav/rann-utsav.jpg"
  ],
  "gujarat/saputara": [
    "/images/packages/gujarat/saputara/saputara.jpg"
  ],
  "gujarat/statue-of-unity": [
    "/images/packages/gujarat/statue-of-unity/statue-of-unity.jpg"
  ]
};
